### ISSUE TITLE
데이터 fetch 관련 Todo

### ISSUE THREAD

**Issue by Deanioche** [ft-ts/frontend#2]
- [x] 전역 변수 관리할 api 필요 ( contextAPI, redux, ... 결정 필요)
       - [ ] 로그인 후 access-token 저장할 장소
- [x] 컴포넌트 마다 각각 SSR, CSR 필요한 부분에 대해 나눠야
- [x] fetch -> axios로 바꿔서 interceptor로 요청 간소화 

cpp 부터 하고 해야지...
