### ISSUE TITLE
todo - dohyulee

### ISSUE THREAD

**Issue by Deanioche** [ft-ts/frontend#47]
- [x] 토큰 없이 /main 갔을때 에러
- [x] main에서 뒤로가기 하면 바로 /login으로 가지게 ( 2fa, signup 안뜨게 )
- [x] 검색 기능 삭제
- [x] 말풍선 길이 ( 그냥 냅두기 )
- [x] 톱니바퀴 누르면 유저 프로필 수정창 on ( 유저리스트가 이 컴포넌트에 있음 )
- [x] 회원가입시에도 이미지 업로드 로직 변경
- [x] 중복 로그인 - 접속중인 계정 로그인으로 리다이렉트( 소켓으로 )
- [x] 로그아웃한 토큰 저장해서 재접속 안되게
- [x] 리프레시 토큰 지우기
- [x] 토큰 블랙리스트
- [x] **ip 자동으로 .env에 입력하는 스크립트
- [ ] 아바타 이미지 base64 저장 -> 백엔드에서 이미지 다운
- [x] 데모유저 제거

### 채널
- [ ] DM, channel에서 탈퇴된 유저에 대한 처리?
- [ ] 삭제 후 재생성한 계정인데 채널이 남아있음
- [ ] 매칭이 안잡힌다? (데모유저 + 일반 유저) -> 다시 잡으니 됨
- [ ] 채널 생성할떄
